from shrinking_algorithms.algorithms.factories.abstract_creator import AlgorithmCreator

from shrinking_algorithms.algorithms.factories.kruskal_creator import KruskalCreator
from shrinking_algorithms.algorithms.factories.evol_creator import EvolCreator