from shrinking_algorithms.algorithms.abstract_algorithm import Algorithm
from shrinking_algorithms.algorithms.abstract_factory import AlgorithmFactory

from shrinking_algorithms.algorithms.evol.evol_algorithm import EvolAlgorithm
from shrinking_algorithms.algorithms.kruskal.kruskal_algorithm import KruskalsAlgorithm

from shrinking_algorithms.algorithms.factories.evol_factory import EvolFactory
from shrinking_algorithms.algorithms.factories.kruskal_factory import KruskalFactory

from shrinking_algorithms.algorithms.types import AlgorithmType, _map_to_algorithm_type