from shrinking_algorithms.algorithms.abstract_algorithm import Algorithm

from shrinking_algorithms.algorithms.evol.evol_algorithm import EvolAlgorithm
from shrinking_algorithms.algorithms.kruskal.kruskal_algorithm import KruskalsAlgorithm
from shrinking_algorithms.algorithms.null_algorithm.null_algorithm import NullAlgorithm

from shrinking_algorithms.algorithms.creators.evol_creator import EvolCreator
from shrinking_algorithms.algorithms.creators.kruskal_creator import KruskalCreator
from shrinking_algorithms.algorithms.creators.null_creator import NullCreator

from shrinking_algorithms.algorithms.types import AlgorithmType, map_to_algorithm_type, get_all_algorithm_types

from shrinking_algorithms.algorithms.factory import Factory
